.TH sflock 1
.SH NAME
sflock \- Lock file and execute command.
.SH SYNOPSIS
.B sflock
\fIFILE\fR \fICOMMAND\fR [\fIARGS\fR]...
.SH DESCRIPTION
.B sflock
locks the \fIFILE\fR and executes \fICOMMAND\fR with \fIARGS\fR.
.SH AUTHOR
Written by Christian Hujer.
.SH REPORTING BUGS
Report bugs via <https://github.com/christianhujer/sflock/issues>
.SH COPYRIGHT
Copyright © 2015 Chrsitian Hujer.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
.br
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
